spring:
    datasource:
        continue-on-error: true
        initialization-mode: always
        initialize: true
        password: postgres
        url: jdbc:postgresql://104.248.238.158:5432/trucku
        username: postgres
